

'''
parameters.py - Defines the parameters for a MRJob Approximation Framework
Instance.

Autogenerated by generate.py

'''

# How many reducers should run in parallel?
# Each reducer will evaluate some set of the 
# solutions.
numReducers = 10


# How many total candidate solutions should be
# yielded by a single reducer?
# Example: Yield 100 exam schedules
numSolnsYield = 2

# What's the maximum number of solutions that
# are yielded should be permutations of 
# one solution.
# Example: Yield at most 10 possible permutations 
#          of the same exam schedule course blocks.
#          This ensures that the overall set of yielded
#          solutions will contain some diversity.
numPerSubsol = 2


# How many rounds of annealing should run?
numRounds = 0

# How many starter solutions should be generated?
numSeedSolns = 10

# How many times should we anneal each solution?
numAnnealCalls = 40

# How many solutions should be passed on to the next round of
# annealing?
topK = 50
# How many results should be returned at the end? 
numFinalResults = 5


